services:
    victoriametrics:
        image: victoriametrics/victoria-metrics:v1.109.0
        container_name: victoriametrics
        restart: on-failure:3
        networks:
            universal: null
        # ports:
        #     - 8428:8428
        volumes:
            - /opt/docker/apps/victoriametrics:/storage
        command:
            - --storageDataPath=/storage
            - --httpListenAddr=:8428
            - --httpAuth.username=__USERNAME__
            - --httpAuth.password=__PASSWORD__
            - --retentionPeriod=90d
        # 自动更新标签
        labels:
            com.centurylinklabs.watchtower.enable: true

networks:
    universal:
        external: true