services:
    victoriametrics:
        image: victoriametrics/victoria-metrics:v1.109.0
        container_name: victoriametrics
        user: root
        restart: on-failure:3
        networks:
            universal: null
        ports:
            - 8428:8428
            - 8089:8089
            - 8089:8089/udp
            - 2003:2003
            - 2003:2003/udp
            - 4242:4242
        volumes:
            - /opt/docker/apps/victoriametrics:/storage
        command:
            - --storageDataPath=/storage
            - --graphiteListenAddr=:2003
            - --opentsdbListenAddr=:4242
            - --httpListenAddr=:8428
            - --influxListenAddr=:8089
            - --vmalert.proxyURL=http://vmalert:8880

networks:
    universal:
        external: true
