services:
    victoriametrics:
        image: victoriametrics/victoria-metrics:v1.109.0
        container_name: victoriametrics
        user: root
        restart: on-failure:3
        networks:
            universal: null
        # ports:
        #     - 8428:8428
        volumes:
            - /opt/docker/apps/victoriametrics:/storage
        command:
            - --storageDataPath=/storage
            - --httpListenAddr=:8428
            - --retentionPeriod=1

networks:
    universal:
        external: true
