services:
    dockge:
        image: louislam/dockge:latest
        container_name: dockge
        restart: on-failure:3
        networks:
            universal: null
        # ports:
        #     - 5001:5001
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /opt/docker/apps/dockge:/app/data
            - /opt/docker/compose:/opt/docker/compose
        environment:
            - DOCKGE_STACKS_DIR=/opt/docker/compose
        labels:
            com.centurylinklabs.watchtower.enable: true
            
networks:
    universal:
        external: true
