services:
    redis:
        image: redis:latest
        container_name: redis
        restart: on-failure:3
        networks:
            universal: null
        volumes:
            - /opt/docker/apps/redis:/data/
        # ports:
        #   - 6379:6379
        labels:
            com.centurylinklabs.watchtower.enable: true
networks:
    universal:
        external: true
