services:
    nezha:
        image: ghcr.io/nezhahq/nezha:latest
        container_name: nezha
        restart: on-failure:3
        networks:
            universal: null
        volumes:
            - nezha_data:/dashboard/data
        # ports:
        #     - 8008:8008

volumes:
    nezha_data:
        name: nezha_data
        driver: local
        driver_opts:
            type: none
            device: /opt/docker/nezha/apps
            o: bind
        
networks:
    universal:
        external: true
