services:
    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        restart: on-failure:3
        networks:
            universal: null
        command:
            - --config.file=/etc/prometheus/prometheus.yml # 配置文件路径
            - --storage.tsdb.path=/prometheus # 数据存储路径
            - --web.console.libraries=/etc/prometheus/console_libraries # console_libraries路径
            - --web.console.templates=/et/prometheus/consoles # consoles路径
            - --web.enable-lifecycle # 启用生命周期
            - --web.enable-admin-api # 启用admin api
        volumes:
            - prom_data:/prometheus # 数据存储路径
            - prom_config:/etc/prometheus/prometheus.yml # 配置文件路径
        # ports:
        #   - 9090:9090

networks:
    universal:
        external: true

volumes:
    prom_data:
        name: prom_data
        driver: local
        driver_opts:
            type: none
            device: /opt/docker/prometheus/apps
            o: bind
    prom_config:
        name: prom_config
        driver: local
        driver_opts:
            type: none
            device: /opt/docker/prometheus/config
            o: bind
