services:
    redis:
        image: redis:latest
        container_name: redis
        restart: on-failure:3
        networks:
            universal: null
        volumes:
            - redis_data:/data
        # ports:
        #   - 6379:6379
networks:
    universal:
        external: true

volumes:
    redis_data:
        name: redis_data
        driver: local
        driver_opts:
            type: none
            device: /opt/docker/redis/apps
            o: bind