services:
    vaultwarden:
        image: vaultwarden/server:latest
        container_name: vaultwarden
        restart: on-failure:3
        networks:
            universal: null
        volumes:
            - /opt/docker/vaultwarden/apps:/data
            - /opt/docker/vaultwarden/log:/log
        # ports:
        #   - 80:80
        env_file:
            - vaultwarden.env
        # 自动更新标签
        labels:
            com.centurylinklabs.watchtower.enable: true

networks:
    universal:
        external: true