services:
    mysql:
        image: mysql:8.4.0
        container_name: mysql
        restart: on-failure:3
        networks:
            universal: null
        volumes:
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
            - /opt/docker/apps/mysql:/var/lib/mysql
            - /opt/docker/log/mysql:/var/log/mysql
            - /opt/docker/config/mysql/conf.d:/etc/mysql/conf.d
            - /opt/docker/config/mysql/my.cnf:/etc/my.cnf
        # ports:
        #   - 3306:3306
        env_file:
            - mysql.env
        labels:
            com.centurylinklabs.watchtower.enable: true
networks:
    universal:
        external: true
